# Generated by Django 4.1.3 on 2022-12-05 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_alter_choice_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='question',
            name='Course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=2000),
        ),
    ]
